---
title: Tonih Setark Blog
timezone: Asia/Jakarta
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: tonyapriyadi@student.uir.ac.id
description: 'Hello! Nama saya Tony, pecinta kode dan kopi. Setiap baris kode mempunyai
  cerita dan dengan secangkir kopi kita mendengarkan cerita.

'
baseurl: 
url: http://yourdomain.com
twitter_username: 
github_username: tonihsetark
markdown: kramdown
