# Site settings
title: Tonih Setark Blog
email: tonyapriyadi@student.uir.ac.id
description: > # this means to ignore newlines until "baseurl:"
  Hello! Nama saya Tony, pecinta kode dan kopi. Setiap baris kode mempunyai cerita dan dengan secangkir kopi kita mendengarkan cerita.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  tonihsetark

# Build settings
markdown: kramdown
